#+title: Is Logseq Better than Org Roam?
#+date: [2022-05-06 Fri]
#+video: qjAIXCmhCQQ

* Updates

- Regular videos start back next week!
- I'm planning to diversify topics a bit while continuing Emacs videos

* Is Logseq Better than Org Roam?

I've been experimenting with an interesting tool called Logseq for the last week, and since it has some similarities and relationship to Emacs, I thought it would be interesting for us to take a look at it!

If you're new to this channel, consider subscribing!  I'll be talking more about workflow tools and knowledge management this year.

* What is Logseq?

"A privacy-first, open-source platform for knowledge management and collaboration."

Basically, it's a combination of an outliner and networked knowledge database.

It's inspired by and competes with tools like Notion, Workflowy/Dynalist, Obsidian, and even Emacs, Org Mode and Org Roam to some degree.

It's free software!  Licensed AGPL 3.0: https://github.com/logseq/logseq

Linux users (even Guix users!) can install easily via FlatPak: https://flathub.org/apps/details/com.logseq.Logseq

You can also find other desktop and mobile app builds on GitHub: https://github.com/logseq/logseq/releases/tag/0.6.7

It's got a lot of traction and high-profile users, even acquired a ton of funding (but is that necessarily good?):

https://blog.logseq.com/logseq-raises-4-1m-to-accelerate-growth-of-the-new-world-knowledge-graph/

* Interesting Features

Here are some of the features you might want to experiment with:

- Stores notes as plain text files (Markdown by default)
- Supports user-authored plugins with a built-in plugin "marketplace"
- You can embed both pages and blocks into other pages
- Pages and blocks also support backlink references
- There's a graph view
- It can auto-commit your notes to Git for you and use the repo for note history
- *Can also save notes as Org Mode files!*
- Anything else I'm missing?

Let's take a look!

* So how would I use it?

Let's create an empty "graph", but make sure to set the file type to Org Mode first!

Things to cover:

- Daily logging
- Creating networked notes
- Using the graph view

If you're an Emacs user, you could even use this as an alternative mobile editor to things like Orgzly.

* Is it better than Emacs and Org Mode / Org Roam?

Depends on your use case, but it's possible that you could use them together!

- Use Logseq to edit your Org files on the go (but it might require using only a subset of Org features)
- Use Logseq primarily but sometimes make edits from within Emacs

To me, the downsides of Logseq are:

- You don't get the benefit of your comfortable Emacs setup
- You don't get to generate agenda views from your tasks, instead you have to concoct your own task workflow (not 100% true, Logseq queries can help)
- Not really compatible with Org Roam if you want to use Emacs to edit notes primarily on desktop
- Perhaps not as easy to export your notes to a website (debatable), but it is actually possible!
- No Org Babel, code execution, etc (or is there?)

Any other thoughts?

* The bottom line

This tool is definitely worth checking out!  I'm going to keep using it for now because it gives me a slightly different way to think about how I manage my tasks and personal knowledgebase.

It's very possible that I'll adapt some of the ideas from it back into my own Org configuration!

* Notes
https://github.com/llcc/org-logseq/
