#+title: Welcome!

System Crafters is a community for computer enthusiasts who love to craft their own computing experience.  The content on this site and on YouTube is intended to teach you how to use tools like [[https://www.gnu.org/software/emacs/][GNU Emacs]] and [[https://guix.gnu.org/][GNU Guix]] to craft your computing experience.

* Video Series

Check out the many [[videos/][video series]] we have to help you learn Emacs and Guix in depth!

* Live Streams

We hope you'll join us for our regular *[[live-streams/][live streams]] every Friday at 8am Pacific, 4pm UTC*!

* Projects

We also have community projects you should check out:

- [[github.com/SystemCrafters/crafted-emacs][Crafted Emacs]]: A sensible starting point for hacking your own Emacs configuration.

* Around the Web

- Visit System Crafters on [[https://youtube.com/c/SystemCrafters][YouTube]] or [[https://odysee.com/@SystemCrafters:e][Odysee]]
- Follow David on the [[https://fosstodon.org/@daviwil][Fediverse]]!
- [[http://systemcrafters.chat][Chat]] with the System Crafters Community
- E-mail David - david [at] systemcrafters.net
