#+title: Welcome!

System Crafters is a community and learning resource for computer enthusiasts who are interested in crafting a custom computing experience.

This website is intended to be the /most comprehensive/ reference on the internet for learning how to leverage tools like [[https://www.gnu.org/software/emacs/][GNU Emacs]], [[https://guix.gnu.org/][GNU Guix]], and [[https://en.wikipedia.org/wiki/Linux][GNU/Linux]] to craft a fully customized workflow using Free Software tools!

The [[https://youtube.com/@SystemCrafters][System Crafters YouTube channel]] also contains almost 200 videos and live stream recordings demonstrating and explaining these tools and broader topics!

* Start Here!

If you are just getting started with *GNU Emacs* and want to learn the basics, check out [[file:emacs-essentials/absolute-beginners-guide-to-emacs.org][The Absolute Beginner's Guide to Emacs]]!

From there, check out the [[file:emacs-essentials.org][Emacs Essentials]] series to learn more about the basics of using Emacs and then follow the [[file:emacs-from-scratch.org][Emacs From Scratch]] series to learn how to fully customize Emacs!

Once you're comfortable using Emacs, learn how to use *GNU Guix* to craft a complete, reproducible system configuration by checking out the [[file:craft-your-system-with-guix.org][Craft Your System with GNU Guix]] series!

You can also check out the many [[file:videos.org][video series]] I've made help you learn these tools in depth.

* Live Streams

We hope you'll join us for our regular *[[file:live-streams.org][live streams]] every Friday at 8am Pacific, 4pm UTC*!

* Stay Up to Date!

Check out new News page to see the latest updates for the website and community.  You can also subscribe to RSS Feeds for various parts of the site.

A much better option is to subscribe to the [[file:newsletter.org][System Crafters Newsletter]] below!
