#+title: Privacy Policy

This website uses [[https://plausible.io/privacy-focused-web-analytics][Plausible]] to capture anonymized metrics about the page views it receives.  Plausible is an open-source, privacy-focused analytics service which strives to provide helpful metrics without capturing any personally-identifiable information about visitors.  It claims to be GDPR, CCPA and cookie law compliant.

- [[https://plausible.io/data-policy][Very little information]] about you is captured, none of it personally identifiable
- I don't see any IP addresses for visitors!
- No cookies or browser fingerprinting are used for tracking
- You are not tracked across multiple sites like with Google Analytics
- The analytics data isn't used by or sold to a third party

I am also not trying to obscure the fact that I am using site analytics with tricks like proxying or CNAME facades.  I want you to have a choice about whether you share the basic information that this analytics platform captures.

*Take a look for yourself!*

If you'd like to see the exact information that I see, check out the [[https://plausible.io/systemcrafters.net][public analytics dashboard]].

*Why use analytics?*

I am very interested in improving the content and organization of this site to ensure that people get the most value out of it.  Page analytics help me to understand which topics are more interesting to visitors so that I can make further investments in those areas.  It also helps me to learn when I am receiving traffic from another site!

If you're interested in helping me make this site better, please consider disabling tracker blocking for this domain!

*Any questions or concerns?*

Please send me an e-mail at =david at systemcrafters.net= if you have any concerns about the use of this service, I'd be happy to hear from you.
