#+title: Videos

* Video Schedule

I typically rotate between a few video series each week, so you should see videos from these series coming in this order, one per week:

- Learning Emacs Lisp
- Emacs Essentials
- Craft Your System with GNU Guix

Other series not in this list are usually finished or postponed until new videos get added!

* Video Series

We have a number of video tutorial series to help you get started with system crafting!

** GNU Emacs

*** [[../emacs-essentials/][Emacs Essentials]]

This series intends to teach you everything you need to know about the built-in functionality of GNU Emacs. Emacs beginners should start here, but seasoned Emacs users might learn a few hidden gems too!

*** [[../emacs-from-scratch/][Emacs From Scratch]]

This series is for users who know the basics and now want to create their own modern Emacs configuration.  I take you step by step through the process of building up a fully custom configuration using many packages that are either built-in or authored by the Emacs community.

*** [[../emacs-desktop-environment/][Emacs Desktop Environment]]

This is a more advanced series where I show you how to build an entire desktop environment with Emacs and EXWM on Linux.  If you want to truly "live" in Emacs, this is for you!

*** [[../learning-emacs-lisp/][Learning Emacs Lisp]]

In this series, I will teach you the core customization language of Emacs called Emacs Lisp.  We start with the basics of the language and then embark on a project to build an Emacs package from scratch!

*** [[../emacs-ide/][Emacs IDE]]

Emacs can also be used as an IDE (integrated development environment) like you might be used to from other editors.  This series will show you how to set up Emacs as an IDE to get rich development functionality for many languages!

*** [[../emacs-mail/][Emacs Mail]]

Emacs can do many things, and this series will show you how you can use it to manage your e-mail!

*** [[../emacs-tips/][Emacs Tips]]

There are many interesting topics we can cover about Emacs that don't require their own dedicated series.  This series is a collection of videos that will cover many other packages and configuration tricks we didn't get to in the other series!

*** [[../mastering-git-with-magit/][Mastering Git with Magit]]

The best interface for Git is in Emacs and it's called Magit!  This series will show you the ropes of how to use Magit to make all of your day to day source control operations ninja fast!

*** [[../advanced-package-management/][Advanced Emacs Package Management]]

Learn more about how to use package managers like straight.el to manage Emacs packages in a more effective way!

*** [[../build-a-second-brain-in-emacs/][Build a Second Brain in Emacs]]

Org Mode gives us the ability to organize our life in Emacs, but we can go even further by building a personal knowledgebase in Emacs using tools like Org Roam!

*** [[../publishing-websites-with-org-mode/][Publishing Websites with Org Mode]]

Org Mode has the ability to export to various other formats including HTML. We can use that capability to publish website directly from Emacs Org Mode.

*** [[../chatting-with-emacs/][Chatting with Emacs]]

Want to chat with the communities around various free and open source projects from the comfort of Emacs?  Check out this series!

** GNU Guix

*** [[../craft-your-system-with-guix/][Craft Your System with GNU Guix]]

GNU Guix is an amazing tool for managing not only the programs you use, but also your entire system configuration.  In this series I will walk you through the process of learning and using Guix step by step so that you can craft your own repeatable system configuration!

** [[../live-streams/][System Crafters Live!]]

This is the Friday live stream series where the System Crafters community gets together discuss news and interesting topics!
