name: Publish to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1

      - name: Check out the style repo
        run: git clone --depth 1 https://git.sr.ht/~daviwil/daviwil.com daviwil.com

      - name: Build the site
        run: |
          cp -R daviwil.com/public .
          emacs --batch -l ./publish.el --funcall dw/publish

      - name: Publish generated content to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
        with:
          dir: public
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}
